@api = http://localhost:3000/api
@apideploy = https://fabrica2022.vercel.app/api
@id = 6352dbaae0a221a13ce7b74a

GET {{api}}/telas

### POST
POST {{apideploy}}/telas
Content-Type: application/json

{"nombre":"Tela 1", "precio":8}

### PUT
PUT {{api}}/telas/{{id}}
Content-Type: application/json

{"title":"Titulo 2",
"description":"Descripción 2"}


### DELETE
DELETE {{api}}/telas/{{id}}