@api = http://localhost:3000/api
@apideploy = https://fabrica2022.vercel.app/api
@id = 6411f6902a271fda1fd3012d

@colection = avios


GET {{api}}/{{colection}}


###GET
GET {{api}}/{{colection}}/{{id}}


### POST
POST {{api}}/{{colection}}
Content-Type: application/json

{
    "nombre": "1",
    "precio": 2,
    "unidad": "ssss",
    "linea": "m",
    "componentes": [
      "Jersey"
    ]
  }

### PUT
PUT {{api}}/{{colection}}/{{id}}
Content-Type: application/json

  {
    "nombre": "1",
    "precio": 2,
    "unidad": "ssss",
    "linea": "m",
    "componentes": [
      "Jersey"
    ]
  }



### DELETE
DELETE {{api}}/telas/{{id}}